export type DestinationLanguage = "KO" | "EN";

// 인천공항 출발편에서 자주 보이는 목적지의 FIDS용 영문 표기.
// API가 한국어 공항명을 내려주는 경우에도 airportCode를 기준으로 영문명을 안정적으로 표시한다.
const DESTINATION_EN: Record<string, string> = {
  // Korea / Japan
  CJU: "JEJU",
  PUS: "BUSAN/GIMHAE",
  NRT: "TOKYO/NARITA",
  HND: "TOKYO/HANEDA",
  KIX: "OSAKA/KANSAI",
  ITM: "OSAKA/ITAMI",
  FUK: "FUKUOKA",
  CTS: "SAPPORO/NEW CHITOSE",
  NGO: "NAGOYA/CHUBU",
  OKA: "OKINAWA/NAHA",
  SDJ: "SENDAI",
  KMQ: "KOMATSU",
  FSZ: "SHIZUOKA",
  HIJ: "HIROSHIMA",
  TAK: "TAKAMATSU",
  MYJ: "MATSUYAMA",
  KMJ: "KUMAMOTO",
  KOJ: "KAGOSHIMA",
  NGS: "NAGASAKI",
  OIT: "OITA",
  KCZ: "KOCHI",
  AOJ: "AOMORI",
  HKD: "HAKODATE",
  KIJ: "NIIGATA",
  TOY: "TOYAMA",
  YGJ: "YONAGO",
  TKS: "TOKUSHIMA",
  UBJ: "YAMAGUCHI/UBE",

  // China / Hong Kong / Macau / Taiwan
  PEK: "BEIJING/CAPITAL",
  PKX: "BEIJING/DAXING",
  PVG: "SHANGHAI/PUDONG",
  SHA: "SHANGHAI/HONGQIAO",
  CAN: "GUANGZHOU",
  SZX: "SHENZHEN",
  TAO: "QINGDAO",
  TSN: "TIANJIN",
  DLC: "DALIAN",
  SHE: "SHENYANG",
  HGH: "HANGZHOU",
  NKG: "NANJING",
  WUH: "WUHAN",
  XIY: "XI'AN",
  CKG: "CHONGQING",
  TFU: "CHENGDU/TIANFU",
  CTU: "CHENGDU/SHUANGLIU",
  KMG: "KUNMING",
  CSX: "CHANGSHA",
  XMN: "XIAMEN",
  FOC: "FUZHOU",
  WUX: "WUXI",
  CGO: "ZHENGZHOU",
  HRB: "HARBIN",
  YNT: "YANTAI",
  WEH: "WEIHAI",
  TNA: "JINAN",
  CGQ: "CHANGCHUN",
  HAK: "HAIKOU",
  SYX: "SANYA",
  NGB: "NINGBO",
  URC: "URUMQI",
  KWE: "GUIYANG",
  HFE: "HEFEI",
  SJW: "SHIJIAZHUANG",
  YNJ: "YANJI",
  WNZ: "WENZHOU",
  JJN: "QUANZHOU/JINJIANG",
  LJG: "LIJIANG",
  DYG: "ZHANGJIAJIE",
  HKG: "HONG KONG",
  MFM: "MACAU",
  TPE: "TAIPEI/TAOYUAN",
  TSA: "TAIPEI/SONGSHAN",
  KHH: "KAOHSIUNG",
  RMQ: "TAICHUNG",

  // Southeast Asia
  BKK: "BANGKOK/SUVARNABHUMI",
  DMK: "BANGKOK/DON MUEANG",
  CNX: "CHIANG MAI",
  HKT: "PHUKET",
  SIN: "SINGAPORE",
  KUL: "KUALA LUMPUR",
  BKI: "KOTA KINABALU",
  PEN: "PENANG",
  SGN: "HO CHI MINH CITY",
  HAN: "HANOI",
  DAD: "DA NANG",
  CXR: "NHA TRANG/CAM RANH",
  PQC: "PHU QUOC",
  MNL: "MANILA",
  CEB: "CEBU",
  CRK: "CLARK",
  CGK: "JAKARTA",
  DPS: "BALI/DENPASAR",
  BWN: "BANDAR SERI BEGAWAN",
  VTE: "VIENTIANE",
  LPQ: "LUANG PRABANG",
  PNH: "PHNOM PENH",
  SAI: "SIEM REAP/ANGKOR",
  RGN: "YANGON",

  // South / Central Asia
  DEL: "DELHI",
  BOM: "MUMBAI",
  BLR: "BENGALURU",
  MAA: "CHENNAI",
  KTM: "KATHMANDU",
  CMB: "COLOMBO",
  DAC: "DHAKA",
  TAS: "TASHKENT",
  ALA: "ALMATY",
  NQZ: "ASTANA",
  FRU: "BISHKEK",
  UBN: "ULAANBAATAR",
  ULN: "ULAANBAATAR",

  // Middle East
  DXB: "DUBAI",
  AUH: "ABU DHABI",
  DOH: "DOHA",
  IST: "ISTANBUL",
  RUH: "RIYADH",
  JED: "JEDDAH",
  TLV: "TEL AVIV",

  // Europe
  LHR: "LONDON/HEATHROW",
  LGW: "LONDON/GATWICK",
  CDG: "PARIS/CHARLES DE GAULLE",
  FRA: "FRANKFURT",
  MUC: "MUNICH",
  FCO: "ROME/FIUMICINO",
  MXP: "MILAN/MALPENSA",
  AMS: "AMSTERDAM",
  MAD: "MADRID",
  BCN: "BARCELONA",
  ZRH: "ZURICH",
  VIE: "VIENNA",
  PRG: "PRAGUE",
  BUD: "BUDAPEST",
  WAW: "WARSAW",
  HEL: "HELSINKI",
  CPH: "COPENHAGEN",
  OSL: "OSLO",
  ARN: "STOCKHOLM/ARLANDA",
  ATH: "ATHENS",
  LIS: "LISBON",
  BRU: "BRUSSELS",
  ZAG: "ZAGREB",
  TBS: "TBILISI",

  // North America
  LAX: "LOS ANGELES",
  SFO: "SAN FRANCISCO",
  SEA: "SEATTLE",
  JFK: "NEW YORK/JFK",
  EWR: "NEW YORK/NEWARK",
  IAD: "WASHINGTON/DULLES",
  BOS: "BOSTON",
  ORD: "CHICAGO/O'HARE",
  DFW: "DALLAS/FORT WORTH",
  ATL: "ATLANTA",
  LAS: "LAS VEGAS",
  HNL: "HONOLULU",
  YVR: "VANCOUVER",
  YYZ: "TORONTO",
  YUL: "MONTREAL",

  // Oceania / Pacific
  SYD: "SYDNEY",
  MEL: "MELBOURNE",
  BNE: "BRISBANE",
  AKL: "AUCKLAND",
  GUM: "GUAM",
  SPN: "SAIPAN",
  ROR: "KOROR/PALAU",
};

export function destinationName(
  airportCode: string,
  koreanName: string,
  language: DestinationLanguage
) {
  if (language === "KO") return koreanName || airportCode || "-";

  const code = airportCode.trim().toUpperCase();
  const mapped = DESTINATION_EN[code];
  if (mapped) return mapped;

  // API가 이미 영문명을 반환하는 경우는 그대로 사용한다.
  if (koreanName && /^[\x00-\x7F\s/.'’()-]+$/.test(koreanName)) {
    return koreanName.toUpperCase();
  }

  // 아직 사전에 없는 신규 취항지는 코드라도 틀리지 않게 표시한다.
  return code || koreanName || "-";
}
